version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_sistema
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend_sistema
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_sistema
    ports:
      - "3000:80"
